name: GriefDefenderFix
version: 1.2
author: UselessMnemonic
description: Removes GriefDefender owner tags from player related inventories.
website: https://github.com/UselessMnemonic

main: me.uselessmnemonic.griefdefenderfix.Fix
depend: [GriefDefender]
load: POSTWORLD

api-version: 1.16

commands:
  sanitize:
    description: Sanitizes a player's inventory
    usage: /<command> [player]